### ISSUE TITLE
Some trouble

### ISSUE THREAD

**Issue by Lisse1024** [jingrk/HDBN#1]
May I ask if this is due to my file structure being incorrect, or is it that the author hasn't shared it?
FileNotFoundError: [Errno 2] No such file or directory: './cluster_users/users_C0.csv'

**Comment by jingrk** [comment]
Thank you for reaching out and for your interest in the code I shared. I'm sorry for the inconvenience caused by the error you encountered.
This error is due to the lack of user-music interaction data for each user group. For example, the file users_C0.csv contains data for users who belong to Group 1. I did not upload these data. User grouping was performed based on the user-music interaction history using methods such as K-Means. Once the user groups are formed, save the user-music interaction records within the same group into separate files, such as users_Cn.csv, where n corresponds to the group index.
To speed up the training process and testing, the training set, validation set, and test set data were saved separately according to user groups.
I will organize and upload the grouped data of our experiment for your reference in the next few days. You can also perform your own data partitioning and train the user's music mood preference models and put them under the ./pretrained_psi folder.

**Comment by Lisse1024** [comment]
Thanks for the author's help and prompt feedback, but I have encountered a new error, and now the confusion is whether such files need to be provided by the author as well. And inside configs.py I see a lot of files with npy suffix ......
FileNotFoundError: [Errno 2] No such file or directory: './user2cluster.npy'

**Comment by jingrk** [comment]
Thank you very much for your feedback.
I have uploaded the user2cluster.npy file. When conducting experiments with the grouping data (such as the users_C0.csv file), you will not need the data in user2cluster.npy. If you encounter any issues with missing data files, please first check the data folder to see if the corresponding file is present. If the file exists, ensure that the correct path is configured in configs.py. If the file is missing, please let me know, and I will upload the required file. Thank you again.

**Comment by Lisse1024** [comment]
Thank you very much for the author's response again. Perhaps I haven't clarified the entire logic of the code yet, so I have many questions, and I apologize for that. But there may still be files that haven't been uploaded, such as years.npy, genres.npy, artists.npy, UI_indexes_train.csv, UI5_index_validation.csv, and UI5_index_validation.csv.

**Comment by jingrk** [comment]
I have uploaded the following files: genres.npy, artists.npy, years.npy, UI_indexes_train.csv, UI5_index_validation.csv, and UI5_index_validation.csv. The UI_indexes_train.csv, UI5_index_validation.csv, and UI5_index_validation.csv files are equivalent to the merged .csv files under the corresponding cluster_users_{train/eval/test} paths.
Thank you for your feedback. If you have any other questions, please let me know.

**Comment by Lisse1024** [comment]
Thank you for the author's sharing. I have obtained the new files and started trying to run the project, but I encountered a few issues and would like to ask the author:
 1. It seems that the author did not provide the 'l2_lambda' parameter. What would be an appropriate value for this parameter? 
 2. The file in ./data/EmoMusicLJ/cluster_users_valid/users_C{group_}.csv does not seem to be shared. Currently, there are only cluster_users_eval, cluster_users_test, and cluster_users_train. 
I apologize for the inconvenience.

**Comment by jingrk** [comment]
I apologize for the missing data descriptions and parameter settings.
(1) In our experiments, we set l2_lambda to 5e-6 for EmoMusicLJ and 5e-5 for EmoMusicLJ-small. You may also perform a grid search to determine a more optimal l2_lambda configuration.
(2) cluster_users_eval is namely cluster_users_valid.

**Comment by Lisse1024** [comment]
Thank you for your prompt reply. I used the parameters you provided and correctly set the file path. After running it, this problem occurred:
Traceback (most recent call last):
  File "F:\HDBN-main\hdbn\HDBN.py", line 267, in <module>
    HR, NDCG = evaluate_all_emo(valid_uies, SCORE, ui_train, hyper_param['top_K'], process_num=1)
  File "F:\HDBN-main\utils\evaluation.py", line 106, in evaluate_all_emo
    return evaluate_one_ui_emo(eval_uies,UI_score,ui_train,top_K_list)
  File "F:\HDBN-main\utils\evaluation.py", line 49, in evaluate_one_ui_emo
    scores = np.delete(scores, train_u_items)
  File "D:\python\envs\program_python39\lib\site-packages\numpy\lib\_function_base_impl.py", line 5567, in delete
    keep[obj,] = False
IndexError: index 6132 is out of bounds for axis 0 with size 6095

I haven't solved this problem, and I would appreciate the author's possible assistance.

**Comment by jingrk** [comment]
This issue is caused by the music track index being out of bounds. Please replace the number 6095 in HDBN.py with the actual number of music tracks in EmoMusicLJ and EmoMusicLJ-small. For example, EmoMusicLJ contains 6180 unique music tracks. To simplify, you can define a variable Song_Num to represent the number of music tracks and set this variable accordingly for different datasets.

**Comment by Lisse1024** [comment]
Thank you for the author's help, I have successfully run the code. HDBN.py has completed 100 training rounds. But how should I visualize the model's recommendation results next? I plan to implement this great music recommendation using front-end and back-end, so please rest assured, I will only use it for academic research. I also ask for your guidance.

**Comment by jingrk** [comment]
You can save the trained model parameters and create an application on the back end to load the trained model. When generating recommendations, run the eval_score variable of the trained model and pass the user and music features required by feed_dict to get the user's music preference scores. Then, according to the preference scores, top-n recommendation results are generated from high to low for front-end display.
